type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files:
  - \.gz$
  - setup.*log$
  - management_playbooks.log
  - management_playbooks.log.*
multiline:
  pattern: '^\d\d\d\d-\d\d-\d\d'
  match: after
  negate: true

fields:
{{ range $k, $v := .fields }}
 tower.tower.{{$k}}: {{$v}}
{{ end }}
fields_under_root: true
