type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]
multiline:
  pattern: "^\\s"
  match: after

fields:
{{ range $k, $v := .fields }}
 tower.tower.{{$k}}: {{$v}}
{{ end }}
fields_under_root: true
processors:
  - add_locale: ~
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.6.0
