- hosts: localhost
  gather_facts: false
  vars:
    sosreport_base_dir: "/thelogs"
  tasks:
    - name: "check vars"
      fail:
        msg: "sosreports_dir is not defined"
      when: sosreports_dir is not defined

    - name: "Create local modules.d dir"
      local_action:
        module: file
        state: directory
        path: modules.d

    - name: "Template docker compose"
      template:
        src: "docker-compose.yml.j2"
        dest: "docker-compose.yml"
        mode: '644'

    - name: "Find sos reports"
      set_fact:
        sosreports: "{{ lookup('find_sosreports', sosreports_dir, wantlist=True, recursive=True) }}"

    - name: "Ensure we found at least 1 sos report"
      fail:
        msg: 'Failed to find any sosreports in "{{ sosreports_dir }}". Please make sure the directory exists and contains at least 1 sos report.'
      when: "sosreports | length == 0"

    - name: "Report number of SOSReports found"
      debug:
        msg: "Found {{ sosreports | length }} sosreports"

    - name: "Template filebeat modules"
      template:
        src: "{{ item.src }}"
        dest: "modules.d/{{ item.dest }}"
        mode: '644'
      with_items:
        - src: "nginx.yml.j2"
          dest: "nginx.yml"
        - src: "tower.yml.j2"
          dest: "tower.yml"

