description: Pipeline for parsing Tower messages.
processors:
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- grok:
    field: message
    patterns:
    - '%{TIMESTAMP_ISO8601:tower.tower.timestamp}%{SPACE}%{NOTSPACE:tower.tower.level}%{SPACE}%{NOTSPACE:tower.tower.logger}%{SPACE}%{GREEDYMULTILINE:message}'
    pattern_definitions:
      GREEDYMULTILINE: |-
        (.|
        )*
    ignore_missing: true
- date:
    if: ctx.event.timezone == null
    field: tower.tower.timestamp
    target_field: '@timestamp'
    formats:
    - yyyy-MM-dd HH:mm:ss,SSS
    on_failure:
    - append:
        field: error.message
        value: '{{ _ingest.on_failure_message }}'
- date:
    if: ctx.event.timezone != null
    field: tower.tower.timestamp
    target_field: '@timestamp'
    formats:
    - yyyy-MM-dd HH:mm:ss,SSS
    timezone: '{{ event.timezone }}'
    on_failure:
    - append:
        field: error.message
        value: '{{ _ingest.on_failure_message }}'
- remove:
    field: tower.tower.timestamp
- set:
    field: event.kind
    value: event
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
