// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package tower

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "tower", asset.ModuleFieldsPri, AssetTower); err != nil {
		panic(err)
	}
}

// AssetTower returns asset data.
// This is the base64 encoded gzipped contents of module/tower.
func AssetTower() string {
	return "eJx8kkFv2kAQhe/+FU8+gy9tLz5Uoi1UiRKInEQ5ogWP1yvWO9buEPC/j2wQGDCZm5/ezPv8tGNsqEkhvCMfAWLEUoq4+44jIKew9qYWwy7F7wgAnjnfWkLBHrXywTiNiQtmZQlv7RosaxTGUkgiIJTsZblmVxidQvyWIqAwZPOQdufGcKqiM0I70tSUQnve1kdlgKOdWXcIhecKUtLhyCVAO/28e5k3KS+WVCCoPO/rPTftVVW3dfWcR63nuv2XIaIzk6VPsj39iuqJ9YDlhPJv+uf9/wgP89lihI9JNh9hmmWL7MJ9QBLay1A+a31RynUtjZTsjjZIqQSaHHkllENKE7r6yYlvkmFGtdsnlTIuERU2y0o5dR34LWBFIShN9wn/shNyEsBF9yhanqGlE1D8Ksq3+I+8wo+fv+J7MF8BAAD//yA+6LQ="
}
